### ISSUE TITLE
Netbeans Error while launching the Application

### ISSUE THREAD

**Issue by sialcasa** [sialcasa/jfx-nested-controllers-example#1]
Executing E:\windocs\Documents\NetBeansProjects\testor\dist\run1684577147\testor.jar using platform C:\Program Files\Java\jdk1.8.0/bin/java
Exception in Application start method
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:367)
at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:305)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:894)
at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
at java.lang.Thread.run(Thread.java:744)
Caused by: javafx.fxml.LoadException:
file:/E:/windocs/Documents/NetBeansProjects/testor/dist/run1684577147/testor.jar!/de/saxsys/fxml/MainView.fxml:9

at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2617)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3230)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3191)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3164)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3140)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3120)
at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3113)
at de.saxsys.fxml.Starter.start(Starter.java:14)
at com.sun.javafx.application.LauncherImpl$8.run(LauncherImpl.java:837)
at com.sun.javafx.application.PlatformImpl$7.run(PlatformImpl.java:335)
at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:301)
at com.sun.javafx.application.PlatformImpl$6$1.run(PlatformImpl.java:298)
at java.security.AccessController.doPrivileged(Native Method)
at com.sun.javafx.application.PlatformImpl$6.run(PlatformImpl.java:298)
at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
at com.sun.glass.ui.win.WinApplication$4$1.run(WinApplication.java:112)
… 1 more
Caused by: java.lang.IllegalArgumentException: Unable to coerce     to class javafx.scene.Node.
at com.sun.javafx.fxml.BeanAdapter.coerce(BeanAdapter.java:495)
at javafx.fxml.FXMLLoader$ValueElement.getListValue(FXMLLoader.java:801)
at javafx.fxml.FXMLLoader$ValueElement.processCharacters(FXMLLoader.java:884)
at javafx.fxml.FXMLLoader.processCharacters(FXMLLoader.java:2852)
at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2537)
… 19 more
Exception running application de.saxsys.fxml.Starter
Java Result: 1

**Comment by sialcasa** [comment]
Did you imported it like this?

![1](https://cloud.githubusercontent.com/assets/2293431/3570184/7629c32e-0b4b-11e4-8a76-b59d027a7c11.png)
![2](https://cloud.githubusercontent.com/assets/2293431/3570185/76f6365c-0b4b-11e4-9d6d-df6d63a7d700.png)
![3](https://cloud.githubusercontent.com/assets/2293431/3570187/7a7237ae-0b4b-11e4-9114-93c06f833de0.png)
